import Head from 'next/head'
import About from '../components/about'
import Blogsec from '../components/blogsec'
import Contact from '../components/contact'
import Intro from '../components/intro'
import Nav2 from '../components/Nav2'
import Portfolio from '../components/portfolio'
import Services from '../components/Services'
import Socials from '../components/Socials'
import Testimonials from '../components/testimonials'
import styles from '../styles/Home.module.css'
import { motion } from "framer-motion"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ephrain Ngowi - Digital branding through website development and Digital Marketing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className={styles.main}>
        <Nav2/>
        <Intro/>
        <About/>
        <Services/>
        <Portfolio/>
        <Blogsec/>
        <Testimonials/>
        <Contact/>
      </main>

      <footer className={styles.footer}>
        <Socials/>
        <p>
          Copyright @ 2022 - All rights Reseved
        </p>
      </footer>
    </div>
  )
}
